sudo: false
language: go
go:
- 1.10.x
cache:
  directories:
  - "$GOPATH/pkg/dep"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: nrFmDZELENKjNgsRdCa9jz+bXgXxjxVvQohwa5jT45/iBHhDELoJpgW9cYs4ZkOkM2MAWaqdlc/XVC3OQ4274RD30LDYXNllprzJUxfXyPZZ5A0lrksWVLy/+uuIkTFmhb5EuKPFjotetZ/csBiiYYKC8TxbwIxpb2DsC86T3vP7ZvGKIQvIX+DZ9M6lD8SsiGbZdHme923ACD4vfCWRZT97aVqxNKI7dbpy/iq5/ZFA9diQ7WBIj9ZxCdg+LQrASYaZVsXyn0ePjIJuk/q5O8teIwNW0aagcTshBt8Y4Kqmg+orVYqtioP+y7LqU4IuFZhD5JzFAWWJ3DSFecSNs2Xra8I5UpfedQFIJ4ZmfYhUZKSvADrNl+5BuAnHp9CER6279hXrp2G8kTmBmXO89Xq7Bm9dgZmpNRR3FCDxaDf+x/7vaRRYg8qpCYOmk3fKkN+NQIYfE88Fs7SdTtKmm1Ql1MC/Yh2J6qLw8/MLKIpK6V43TQ9Cr8ZyfzSI2zH6BSHlD0lvQrLe+qi5LKxLDHn3NhOWQZMq/Gko1JXWBOkqj2cqCYjKTP0QzjDSczSuWDsC2dYJ25HhuO9V1ZFx7h/2AxciRozpeG4jnqYKyGSqLtfN7vr6NRlrQY00H+/ZzYC5WzrRKLZqdC3w2RHpCYM8Ci1aj7npHUadQ8uaKiY=
  - secure: UnvZQaspzcQeF9s213OvBRPP2uCZ0TWFLE8gJAR09HiOZHtRVjwXC0E+oT7tqAAnM+mQNNjfzILbPc8ZhlD9xbtkHrTrr9r0AndvJ6FvN8wdhYJPDclI8UF8qvjtZ1f3k0LCFUA7B03crlUPG+/jST2dv9FzZqz6XhFiwu6fKYuZLcim8/Ck1o4pTVF7Xf3QhTMw7Xu21GhogcX2dMen0/asSy9TfsasH0Awd1f4fkh1idYPKdreE8xTzejMdCb0i0jMaKhd5peXSze2ox4HDL3cGGtrXA9RJahhsm0ANKMoRtQdlVJvBBfatDngP3Hr7bUzWWiyHn04DJ8toqdda/UzaMqtCF0vCx/jDSC4UA2QhrONbKCiNdScKtGsot/n7lLU+npvaIW6NTsFt/Q7olzr5a1f380EeNkdduEKBnm8GuNw6qrOdGfZ5+ITAC/ax9uWUTSvhYBxn0ya4Efdyi3aQXdYZ+haTzpIilZFjLO8tCOrVKhZ4BjrRQ3H81aQxs4x5pp/0+0RPmhlSPLAOHVcN/swR3pQmXCPLE8YHQ622jl6mukMngaxJI4W6Bk6/GxW6wyku8Rx6ddXjnohvuIXrH/TbcDZ5SI/gsvpWpmUXSgu9OEPpUgeK+SjTdg0ly5QBvTV811bDvgCpzSu7aD+Ptpdh6LGHSTScLAI4yo=
  - secure: JtGKoGUE1dwDAT/xC3Qo/heRGWOroYGmu8eh44qumHLEaBjQq7fnFJ6RODrIGOWtqMV3DQKpd+oU90EgOAtUik8sRt24uPdjomLm/VWqt2yZp5DCZKeg7UeV/WZWgpiDbpON/gCdtK7zHLWlMA3IPmDR0eE2UJqKm9NAY8zzSPOweW6elbCiKIYig5Aad29EhgKbmwsPqzoczGBBpNPpbXiOlMH5F9yKnmVW+BdsLRDYvw1zlHB8k/28m2lSaaL35bBUU1I8HBe8at7Fcg+9lUfizdOTv2oCY+lFm0Q5oH7CBIrDM+p4LmqxZ0w84zOaimP5SLpbcsNvGGVAUr4DcigW5xvBhw3KNu9Nwek8ACoKqKLTGRj1HBcRwgqbkqhFrSk9KofgYoBiy4bZAgwyuDH1SsO9jbmwtxxRCOwApc/JdrztGd9Y9GKIkOVWEYl7HNVTbjr8B4q6N5adGCJcec5qvHwz/i1eKOs4A86G7zEYWGjZrdvkif4a7BGo00qlCouANYZMpGlCyH2vxQpIpAaQyV+k0TezB7tNienVk6oKEK2vfq9Smyx+JKVm7/8IMEMjdPMu8h3C13S1KKw4XFHyzzh02QOibWSZNwW45b5jDjZ5w/A1ajtKY66vIBmrS/IE4KoBEaj1DAl7HLp3BqSKqpXKbNAvp+dzGcwzFNM=
before_deploy:
- GOOS=linux GOARCH=amd64 go build  -o kubsrv_Linux_x86_64
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=ksmster/kubsrv
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 
  file:
  - kubsrv_Linux_x86_64
  on:
    tags: true
    repo: skabashnyuk/kubsrv
  api-key:
    secure: aJCm+RrLdc/cLs0RQ+u1tsXZJgv7Sszb5X2BfuNcfCPh7LukGU5nGPrhzDbFK2yBlA6A+8WrMkqUxE7T83uWA7rr5oggoytngrC1pveFOaD0eni1pQenDGu+lzXnNUeOP+ApQ0e7VUnLem+bC8yxKEC4i5T17othyjua+01uWzrOpaG4mDfUYJIDuttMqkkVkPleNDEv260BlOvvmrCSCmRuwkxMT5lYLD2JUfo/Ee13yfbtXR3Oa/G2cfQQL8q0dbfszaVxoGGTSROXolLLty6nAHK3hgcr32TrVZanGgMM4FsKvlDdtvRxNMEwuYVvKmTGYuCNcAUx0D0gzuth5ht0l0kX9q8CayahFVILh/PxbAekQU/gXxCpKDyWQpWDjdsg2X0lav6ET9+t7RdMJEAJzg52Ivms2gaiYaRXEWXaTKzVfByl8tWFD0LZla9hOyah+Q9MUsCNX4he21X/rU99WATdmZJqmGxRWJttXkM91acursAUlTNKa8f9WWsjSMhbA0Im7nRTx2yKZqlsHcaIvFDnoBtV9gvIxIuqhRnr58No4C47SHNb+i4waw46IUQOv8hGD4VRSFVZ98ZXEIZYJKp3VGzx9crUjf3Pl7pwDiFKpJ2PILKH7i2+25M13uMD7wpzxKLfISufbTGMMEAVObSyAydtayBATw19DWA=
before_install:
- go get -u github.com/golang/dep/cmd/dep
install:
- dep ensure
script:
- go test ./...
notifications:
  email: false
