sudo: false
language: go
go:
  - 1.10.x

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/pkg/dep


before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go test ./...

notifications:
  email: false